version: '2'

services:
  node-dev:
    container_name: node-dev
    build:
      context: .
      dockerfile: Dockerfile
    image: yanhao/docker-node-dev
    hostname: node.dev
    ports:
      - "8000:8000"
    volumes:
      - ./src:/src
      - $SSH_AUTH_SOCK:/ssh-agent
      - "${HOME}/.vbuf:/home/docker/.vbuf"
    environment:
      - SSH_AUTH_SOCK=/ssh-agent
    working_dir: /src
